import type { PathPlannerPromptVariantId } from './index'

export const PATH_PLANNER_PROMPT_VARIANT_ALIASES: Record<string, PathPlannerPromptVariantId> = {
  default: 'implementation',
  implementation: 'implementation',
  current: 'implementation',
  prod: 'implementation',
  production: 'implementation',
  '1': 'exp1_meaningful',
  exp1: 'exp1_meaningful',
  exp1_meaningful: 'exp1_meaningful',
  meaningful: 'exp1_meaningful',
  '2': 'exp2_unwalked_required',
  exp2: 'exp2_unwalked_required',
  exp2_unwalked_required: 'exp2_unwalked_required',
  unwalked: 'exp2_unwalked_required',
  '3': 'exp3_unwalked_branch_first',
  exp3: 'exp3_unwalked_branch_first',
  exp3_unwalked_branch_first: 'exp3_unwalked_branch_first',
  branch_first: 'exp3_unwalked_branch_first',
  '4': 'exp4_unwalked_long_paths',
  exp4: 'exp4_unwalked_long_paths',
  exp4_unwalked_long_paths: 'exp4_unwalked_long_paths',
  long_paths: 'exp4_unwalked_long_paths',
  '5': 'exp5_journey_deepening',
  exp5: 'exp5_journey_deepening',
  exp5_journey_deepening: 'exp5_journey_deepening',
  journey: 'exp5_journey_deepening',
  '6': 'exp6_comprehensive',
  exp6: 'exp6_comprehensive',
  exp6_comprehensive: 'exp6_comprehensive',
  comprehensive: 'exp6_comprehensive',
  '7': 'exp7_risk_first',
  exp7: 'exp7_risk_first',
  exp7_risk_first: 'exp7_risk_first',
  risk: 'exp7_risk_first',
  '8': 'exp8_portfolio_balanced',
  exp8: 'exp8_portfolio_balanced',
  exp8_portfolio_balanced: 'exp8_portfolio_balanced',
  portfolio: 'exp8_portfolio_balanced',
}
